#!/usr/bin/env python
import sys
import os

arguments = ''
if len(sys.argv) == 2 and 'stop' in sys.argv[1]:
    arguments = '[Stop]'
else:
    for arg in sys.argv[1:]:
        arguments += str(arg) + ' '

if len(sys.argv) > 1 and 'show' in sys.argv[1]:
    os.system('python ./clock_report.py ' + arguments)
else:
    os.system('python ./clock_add.py ' + arguments)